stages:
  - test
  - sonarqube
  - build
  - push

variables:
  SPRING_PROFILES_ACTIVE: cicd
  FILE_UPLOAD_DIR: uploads
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # cache Sonar
  GIT_DEPTH: "0"                             # clone complet requis par Sonar

test:
  stage: test
  image: maven:3.9-amazoncorretto-21
  script:
    - mvn clean test -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE
  tags:
    - docker
  only:
    - main
    - dev
    - merge_requests

sonarqube-check:
  stage: sonarqube
  image: maven:3.9-amazoncorretto-21
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=pma-dev-backend -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  tags:
    - docker
  only:
    - main
    - dev
    - merge_requests
compile:
  stage: build
  image: maven:3.9-amazoncorretto-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  tags:
    - docker
  only:
    - main
    - dev
    - merge_requests

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - compile
  script:
    - docker build -t 144.91.76.149:5000/monapp-backend:$CI_COMMIT_SHA .
  tags:
    - docker
  only:
    - main
    - dev
    - merge_requests

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push 144.91.76.149:5000/monapp-backend:$CI_COMMIT_SHA
  tags:
    - docker
  only:
    - main
    - dev
    - merge_requests
