services:
  # ---------------------------------
  # MongoDB – stores your Spring data
  # ---------------------------------
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db         # <-- persistent database files

  # ---------------------------------
  # Postgres – Keycloak's production DB
  # ---------------------------------
  db:
    image: postgres:16
    container_name: keycloak_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kc
      POSTGRES_PASSWORD: kcpass
    ports:
      - "5432:5432"
    volumes:
      - kc_db:/var/lib/postgresql/data  # <-- persistent Keycloak schema

  # ---------------------------------
  # Keycloak – identity & access
  # ---------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: kc
      KC_DB_PASSWORD: kcpass
    command: start-dev
    volumes:
    - ./themes/wishborn:/opt/keycloak/themes/my-nest-login

volumes:
  mongo_data:   # persistent volume for MongoDB
  kc_db:        # persistent volume for Postgres